### ISSUE TITLE
Rendering on Android is incorrect / low resolution

### ISSUE THREAD

**Issue by hybridherbst** [quadjr/aframe-gaussian-splatting#12]
Looks like when rendering on some Android devices the output does resemble the splats but looks very low resolution; not sure if incorrect sorting or if something with the data goes wrong. I tested this also with the live page from this repo.

Tested on Xiaomi 11T. Works fine on _other_ Android devices like Quest 3

Some images of how it looks (after all splats have been loaded):
| Image 1 | Image 2 |
| - | - |
| ![image](https://github.com/quadjr/aframe-gaussian-splatting/assets/2693840/2199f11d-1427-420c-950b-91d659fbe20e) | ![170C2CAA-F246-493A-BD20-10F4FDD1DB04](https://github.com/quadjr/aframe-gaussian-splatting/assets/2693840/ef9dfd4c-1df8-401b-a84d-ac1b3e63d991) |

**Comment by quadjr** [comment]
Thank you for the report.
That seems unusual. 

Which browser are you using?
Does this issue occur every time?
Doesn't it resolve even after reloading the page?
Can you see that the number of splats is increasing?

**Comment by hybridherbst** [comment]
- this is latest Chrome
- issue occurs every time on this device
- it does not resolve after reloading the page, it is persistent
- yes, I can see the number of splats increasing (triple checked, it's all of them)

**Comment by quadjr** [comment]
Hmm, I'm not sure what's causing it.
I'll check at a nearby electronics store to see with which devices the issue occurs.
I'll be creating a test script, so please wait for a few days.

**Comment by hybridherbst** [comment]
Some more tests on random devices here:

| Mobile Device | Works (✅) vs Blurry (❌) |  GPU |
| - | - | - |
| iPhone 11 | ✅ | A13 Bionic | 
| iPhone 14 | ✅ | A16 Bionic |
| iPad Pro | ✅ | M2 |
| Quest 2 Browser | ✅ | XR2 Gen 1 |
| Quest 3 Browser | ✅ | XR2 Gen 2 |
| Samsung Galaxy Tab S8 | ✅ | Adreno 730 |
| Xiaomi 11T | ❌ | ARM Mali-G77 | 
| Huawei Mate 20 | ❌ | ARM Mali-G76 | 
| Huawei P30 Pro | ❌ | ARM Mali-G76 | 
| Google Pixel 5 | ✅ | Adreno 620 | 
| Google Pixel 6 | ❌ | ARM Mali-G78 |
| NOKIA 5.4 | ✅ | Adreno 610 |

So seems ARM Mali is the problem.

**Comment by hybridherbst** [comment]
@aras-p maybe you have an idea? Shader code is here: https://github.com/quadjr/aframe-gaussian-splatting/blob/8aa3d91813d6583f124c7fda53d04f800674e442/index.js#L48

**Comment by softyoda** [comment]
The same issue is visible on my smartphone as well.

I have a Huawei P30 Pro and I tested it on Firefox Mobile (118.2.0).



Using the debugging tool about:debugging I managed to get the console log, there are no error, just warning.
<details>
  <summary>Console logs</summary>


```diff
!Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. gaussian-splatting
!Feature Policy: Skipping unsupported feature name “accelerometer”. gaussian-splatting
!Feature Policy: Skipping unsupported feature name “gyroscope”. gaussian-splatting
!Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. gaussian-splatting
!Feature Policy: Skipping unsupported feature name “accelerometer”. gaussian-splatting
!Feature Policy: Skipping unsupported feature name “gyroscope”. gaussian-splatting
!Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. Sample.3c5b792f.js:7:2737
!Feature Policy: Skipping unsupported feature name “accelerometer”. Sample.3c5b792f.js:7:2737
!Feature Policy: Skipping unsupported feature name “gyroscope”. Sample.3c5b792f.js:7:2737
!WebRTC: Using more than two STUN/TURN servers slows down discovery index-f8ccf2d9.js:3760
 Particle system powered by three.quarks. https://quarks.art/ index-f8ccf2d9.js:5826:19254
#Made with ♥ by 🌵 Needle - https://needle.tools — Version 3.20.1 index-f8ccf2d9.js:6754:1857
 @@Needle Engine — No license active, commercial use is not allowed. Visit https://needle.tools/pricing for more information and licensing options. index-f8ccf2d9.js:4337:15@@
!Your model is using scaled mesh colliders which is not optimal for performance Cube 
!Object { x: 0.001, y: 0.001, z: 0.001 }
!index-f8ccf2d9.js:6656:1816260
THREE.!WebGLTextures: sRGB encoded textures have to use RGBAFormat and UnsignedByteType. index-f8ccf2d9.js:3616:38905
!WebGL warning: readPixels: `pixels` type does not match `type`. 6
#download progress: 2.02% 5.77 Mbps index-f8ccf2d9.js:6752:1325
!WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 1 is of type UINT, but the shader samples as FLOAT. 5
#download progress: 4.91% 8.73 Mbps index-f8ccf2d9.js:6752:1325
!WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 1 is of type UINT, but the shader samples as FLOAT. 5
#download progress: 7.27% 9.33 Mbps index-f8ccf2d9.js:6752:1325
!WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 1 is of type UINT, but the shader samples as FLOAT. 5
#download progress: 9.69% 10.43 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 11.77% 10.75 Mbps index-f8ccf2d9.js:6752:1325
!WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 1 is of type UINT, but the shader samples as FLOAT. 5
#download progress: 13.09% 10.71 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 17.00% 11.89 Mbps index-f8ccf2d9.js:6752:1325
!WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 1 is of type UINT, but the shader samples as FLOAT. 5
#download progress: 20.74% 11.75 Mbps index-f8ccf2d9.js:6752:1325
!WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 1 is of type UINT, but the shader samples as FLOAT.
!After reporting 32, no further warnings will be reported for this !WebGL context.
#download progress: 24.33% 11.64 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 26.33% 11.52 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 29.77% 11.58 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 32.71% 11.76 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 35.95% 11.49 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 39.54% 11.80 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 43.18% 11.95 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 46.63% 12.20 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 50.22% 12.03 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 57.05% 12.23 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 58.25% 11.10 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 61.94% 11.41 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 68.72% 11.78 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 72.46% 11.18 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 76.05% 11.30 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 83.09% 11.31 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 86.28% 10.73 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 89.72% 10.71 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 91.32% 10.57 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 95.51% 10.94 Mbps index-f8ccf2d9.js:6752:1325
#download progress: 99.10% 10.73 Mbps index-f8ccf2d9.js:6752:1325
#Completed download. index-f8ccf2d9.js:6752:1201
!An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. index-f8ccf2d9.js:3616:227538
```
</details>

**Comment by quadjr** [comment]
> Some more tests on random devices here:
> 
> Mobile Device	Works (✅) vs Blurry (❌)	GPU
> iPhone 11	✅	A13 Bionic
> iPhone 14	✅	A16 Bionic
> iPad Pro	✅	M2
> Quest 2 Browser	✅	XR2 Gen 1
> Quest 3 Browser	✅	XR2 Gen 2
> Samsung Galaxy Tab S8	✅	Adreno 730
> Xiaomi 11T	❌	ARM Mali-G77
> Huawei Mate 20	❌	ARM Mali-G76
> Huawei P30 Pro	❌	ARM Mali-G76
> Google Pixel 5	✅	Adreno 620
> Google Pixel 6	❌	ARM Mali-G78
> NOKIA 5.4	✅	Adreno 610
> So seems ARM Mali is the problem.

@hybridherbst
Wow, thanks for the great information.
I've made a small change that might fix the issue.
Could you try out the code I pushed to the main branch?"

I assumed that the 'int' in GLSL is 32 bits, but according to ChatGPT, it seems that it is not specified.
Commit id is d26566c.

**Comment by quadjr** [comment]
Another possibility could be a difference in endianness.
I'll try to find a smartphone with ARM Mali.

**Comment by aras-p** [comment]
> Another possibility could be a difference in endianness

No, all GPUs are little endian.

Mali-G7x is a capable GPU, and should fully support both full 32-bit floats, and full 32-bit integers. So my guess would be on "something to do with driver side". Random ideas:

- Even if GLSL ES specification does say that within a vertex shader, both `float` and `int` is `highp`, maybe the driver gets it wrong? i.e. adding `precision highp float; precision highp int;` to the shader source. In theory not needed, in practice, Android drivers {insert grumbling noises}.
- I do remember that "a while ago", basically only ARM Mali GPUs _in theory_ could not do floating point textures (but right now I don't remember whether they could not sample from them, or render into them). That had nothing to do with hardware (the hardware could always do it), but rather something to do with patents. Since then, said patents presumably have expired, and with fairly recent drivers they can do it all as expected. But if you're on old Android version, you might be hitting that issue.

I also wonder why there's a `WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 1 is of type UINT, but the shader samples as FLOAT` in the reported WebGL logs. The shader does declare sampler as `usampler2D` as I would expect. Something gets lost on three.js side?

**Comment by hybridherbst** [comment]
- ❌  https://github.com/quadjr/aframe-gaussian-splatting/commit/d26566c11b546fb953ee8944c0cb3e48d3c7eb36 did not help
- ❌ `precision highp float; precision highp int;` did not help

**Comment by quadjr** [comment]
> > Another possibility could be a difference in endianness
> 
> No, all GPUs are little endian.
> 
> Mali-G7x is a capable GPU, and should fully support both full 32-bit floats, and full 32-bit integers. So my guess would be on "something to do with driver side". Random ideas:
> 
> * Even if GLSL ES specification does say that within a vertex shader, both `float` and `int` is `highp`, maybe the driver gets it wrong? i.e. adding `precision highp float; precision highp int;` to the shader source. In theory not needed, in practice, Android drivers {insert grumbling noises}.
> * I do remember that "a while ago", basically only ARM Mali GPUs _in theory_ could not do floating point textures (but right now I don't remember whether they could not sample from them, or render into them). That had nothing to do with hardware (the hardware could always do it), but rather something to do with patents. Since then, said patents presumably have expired, and with fairly recent drivers they can do it all as expected. But if you're on old Android version, you might be hitting that issue.
> 
> I also wonder why there's a `WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 1 is of type UINT, but the shader samples as FLOAT` in the reported WebGL logs. The shader does declare sampler as `usampler2D` as I would expect. Something gets lost on three.js side?

Thank you for the valuable information.
I'm also curious about the reported WebGL logs. I use one float texture and one uint texture, and utilize sampler2D for the float and usampler2D for the uint.
A-Frame and three.js prepend some lines to the beginning of the shader script, but they don't alter the actual processes.

Given the blurred image, it appears that the color and position are accurate, but the rotation and scale are wrong. This means that the issue lies in the unpacking process.
https://github.com/quadjr/aframe-gaussian-splatting/blob/f9f876ef07ff511ec147489951a54d546f97b195/index.js#L78

**Comment by aras-p** [comment]
Another random thought: isn't `usampler2D` only available since GLSL ES 3.0 (i.e. WebGL2)? Maybe the Mali shader compiler is really more strict than the others, and goes "uhh you are using GLSL ES 1.0 shader, let me ignore usampler2D". Using WebGL2 and `#version 300 es` in the shader would be a fix then (might also need other changes to be done).

Edit: some more checking. Pasting the vertex shader into Shader Playground ([link](https://shader-playground.timjones.io/7cb597c456915c8defa25267d732c64d) but the website is kinda slow), selecting GLSL and Mali Offline Shader Compiler, gives a `ERROR: 0:1: S0028: Expected type for precision qualifier, got 'usampler2D'` so maybe this guess is correct, and you have to use WebGL2 and GLSL ES 3 shaders to get "actual integers coming out of the texture" across the board.

**Comment by hybridherbst** [comment]
So a `ShaderMaterial` in three.js actually prepends some additional data, including glslVersion:
https://github.com/mrdoob/three.js/blob/35a26f178c523514673d992da1aece23c1cfca6e/src/renderers/webgl/WebGLProgram.js#L311
For a non-RawShaderMaterial it's already `#version 300 es`.

I tried turning it into a RawShaderMaterial, which works too when
- specifying `glslVersion: THREE.GLSL3` (which adds that version define)
- changing `attribute uint splatIndex;` to `in uint splatIndex;`
- adding `out vec4 fragColor;` in the fragment shader and setting that

But unfortunately it doesn't change the incorrect rendering.

**Comment by quadjr** [comment]
I've got a Redmi Note 10 JE (Arm Mali-G57), and it works without the issue. 😂

I discovered that I can use AWS Device Farm to reproduce the issue.
I'm learning how to use it.
Please wait a bit longer.

**Comment by koktavy** [comment]
For another data point, I see this issue on Pixel 7 with ARM Mali-G710. I can confirm it occurs across Chrome/Firefox/Samsung Internet. Thanks for your work!

**Comment by quadjr** [comment]
I've got a strange result on Pixel 6a.
When the number of splats is limited, the result is almost same with Safari on Mac.
However, when the number of splats increases, the result on the Pixel 6a becomes blurred.
It means the blurry occurs depends on the number of splats.

![スクリーンショット 2023-10-18 22 26 17（中）](https://github.com/quadjr/aframe-gaussian-splatting/assets/11469775/24f63c31-0319-4c65-ad92-854067022155)
![スクリーンショット 2023-10-18 22 25 59（中）](https://github.com/quadjr/aframe-gaussian-splatting/assets/11469775/f92ef4fc-575b-4a98-ab06-72e409568401)

**Comment by quadjr** [comment]
This seems to be a bug in ARM Mali-G7x.
I'll examine the behavior a little more.

**Comment by quadjr** [comment]
Some splats are not drawn on Pixel 6a.
Left: Pixel 6a, Right: Mac
![スクリーンショット 2023-10-18 22 50 52（中）](https://github.com/quadjr/aframe-gaussian-splatting/assets/11469775/364e5a65-66a2-45be-af0b-2f97f0c15ce9)

**Comment by quadjr** [comment]
I've fixed the issue!
The default precision of the float sampler on Arm Mali G7x is lower than that on other devices.
I used a float sampler to determine the absolute scale of splats, but due to the lower precision, small splats were treated as having a scale of 0.0.
I added `precision highp sampler2D;` to the vertex shader, and the issue has been resolved.
I've tested it on the Pixel 6a, Pixel 6, and Pixel 7.

Thank you all!

**Comment by aras-p** [comment]
Ah! I should have realized this earlier. In retrospect, an extremely obvious issue. All samplers are "low precision" in GLSL ES by default. And I guess other GPU vendors, when reading from a lowp sampler into a full precision float, go "well, just read me full actual float", the Mali presumably does a bit more literal spec interpretation, "sample texture into a low precision variable, and then convert that into a float". Good catch.
